#!/bin/bash

version=""
[[ $1 =~ ^v[1-9]$ ]] && {
	version="$1"
	shift
}

repo="tbt] [PATCH"

files=$(git format-patch -M --subject-prefix="$repo $version" "${@:--1}")

for file in $files
do
	[[ -f /tmp/$file ]] && diff /tmp/$file $file && {
		echo "The same patch /tmp/$file already exists"
		exit
	}
done

git send-email	-q \
		--confirm=never \
		--no-signed-off-by-cc \
		--no-chain-reply-to \
		--to="Pengfei Xu <pengfei.xu@intel.com>" \
		$files

mv -f $files /tmp
